### ISSUE TITLE
[bug] Unable to resolve module ReactDefaultPerf

### ISSUE THREAD

**Issue by weslleyaraujo** [LeoLeBras/react-native-redux-starter-kit#10]
I could not make the app start after following the starter guide:

```
git clone https://github.com/LeoLeBras/react-native-redux-starter-kit.git myAwesomeApp
cd myAwesomeApp
npm i 
```

After opening and build the app in xcode I got this:

<img width="487" alt="screen shot 2016-05-22 at 11 57 19 am" src="https://cloud.githubusercontent.com/assets/2286385/15453396/af320822-2014-11e6-9332-f2d06df76feb.png">

I already tried some of the solutions proposed at the issue [#4968](https://github.com/facebook/react-native/issues/4968) from react-native repo.

Here's some additional info that might be helpful:

```
$ node -v;
v6.0.0

$ npm -v
3.8.6
```

**Comment by LeoLeBras** [comment]
Hey @weslleyaraujo !

Fix https://github.com/LeoLeBras/react-native-redux-starter-kit/commit/4fd6705ad3b622fae9b0ade79760dc28d32213e4 , try `git pull && rm -rf node_modules && npm i && npm start —reset-cache` . 😊 
Feel free to open an issue if it's still not working for you.

**Comment by weslleyaraujo** [comment]
hey @LeoLeBras thanks for that, works fine :)
can you give me some insights why this bug was happening?

**Comment by sibelius** [comment]
npm install installed a version of React different of 15.0.2, probably a more recent one, that doesn't work fine with React Native

**Comment by LeoLeBras** [comment]
Yeah, that's it. Thanks for your answer @sibeliusseraphini !

**Comment by weslleyaraujo** [comment]
thanks guys :)

**Comment by esauter5** [comment]
I got the same error, but when running my tests, so if anyone comes across this, my solution was to update react-native-mocha to 0.2.x

**Comment by uusa35** [comment]
thank you all
