### ISSUE TITLE
Signed APK crashes

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [LeoLeBras/react-native-redux-starter-kit#14]
Hello. I followed the instructions to generate a signed APK (https://facebook.github.io/react-native/docs/signed-apk-android.html#content) using your project as base.
The APK is compiled and installed but when I open it, it crashes (Android API 17)
When I create a fresh new project and follow the same instructions, everything works just fine.
Any ideas about what is happening?

**Comment by LeoLeBras** [comment]
Sorry, this project doesn't support Android.
PRs are welcome 👍

**Comment by rafaelcorreiapoli** [comment]
I want to help, do you have any ideas on where is the problem? (packages, versions...)

**Comment by 0xLevin** [comment]
@LeoLeBras ,why not support Android ?

**Comment by rafaelcorreiapoli** [comment]
@LeoLeBras I figured out where is the problem
Just removed Reactotron and everything worked =)

**Comment by alma-socar** [comment]
I've suffered from same problem @rafaelcorreiapoli had have. Can anybody know how to enable `Reactotron` only in development environment?

**Comment by CharlesMangwa** [comment]
Give a look at their [`ReactNativeExample`](https://github.com/skellock/reactotron/tree/master/examples/ReactNativeExample), it could be helpful!

**Comment by rafaelcorreiapoli** [comment]
@alma-socar I removed it completely, sorry that I can't help you :(

**Comment by CharlesMangwa** [comment]
Closing issue #14
