### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by jamesone** [LeoLeBras/react-native-redux-starter-kit#20]
@LeoLeBras  - Is this being actively maintained?

**Comment by CharlesMangwa** [comment]
Hi! Yes, this project is still alive! We're just working on a huge side project, but an important update is just around the corner 😉…

**Comment by jamesone** [comment]
Good to hear!!! Looking forward to the next update 👍 🎉

**Comment by CharlesMangwa** [comment]
Closing issue #20

**Comment by jamesone** [comment]
Any idea when the update will be merged? Can't seem to find another decent react-native starter! Everything else is over the top and are trying to implement there own tabbars and menus, which is fine to an extent until you have to start implementing more complex functionality! RNRF seems to have it all already.  @CharlesMangwa  @LeoLeBras

**Comment by CharlesMangwa** [comment]
Hi @jamesone ! We plan to push huge modifications next week: stay tuned 😉

**Comment by jamesone** [comment]
Great! Can't wait !!

**Comment by jamesone** [comment]
any idea what day it'll be pushed ;) @CharlesMangwa

**Comment by LeoLeBras** [comment]
Within a day or so ! :tada:

**Comment by jamesone** [comment]
Just checked out the `next` branch! Looks good 😄  I'm seeing a bit of syntax that I've not seen before though? 
E.g React$Element<any>, what's the purpose of this?
`Counter = (props: Props): React$Element<any> => {` 
I also noticed that you're defining types, which is a good thing coming from a Java background :D 
@LeoLeBras

**Comment by CharlesMangwa** [comment]
Hey @jamesone! Glad you like what you've seen so far 😃! 

As you guessed, it allows you to type check a variable to make sure that its input and output values match the types you defined. It's pretty much the same thing as [TypeScript](www.typescriptlang.org).

For instance:

``` js
Counter = (props: Props): React$Element<any> => {
```

means that your variable `props` should match the type `Props` you defined like this:

``` js
type Props = {
   foo: boolean,
}
```

and `React$Element<any>` is a rule defined by Flow itself to represent a React element. I let you see what Flow can do [right there](https://flowtype.org/). We thought that Flow should help you to drastically reduce the amount of non-wanted bugs.

By the way I'm actually working on the new documentation which should explain every new feature and it's purpose 😊
