### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by leonardgithub** [LeoLeBras/react-native-redux-starter-kit#23]
in import { styles } from '@components/NavigationBar', which module provides the @ feature?

**Comment by CharlesMangwa** [comment]
It's a feature directly supported by RN itself. I let you read the related part [in the documentation](https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next#alias) 😉

**Comment by leonardgithub** [comment]
@CharlesMangwa OK, thanks. It means it can not be used in just react-web?

**Comment by CharlesMangwa** [comment]
To be more precise, this feature is originally provide by [node-haste](https://www.npmjs.com/package/node-haste) and directly embedded in React, if I remember correctly. So yes: you can also use it with React.js as you can see in [this example](https://github.com/LeoLeBras/react-apollo-example/blob/master/src/bundles/Feed/containers/FeedContainer/index.js#L4-L8)

**Comment by leonardgithub** [comment]
@CharlesMangwa Thanks. You do me a favor

**Comment by CharlesMangwa** [comment]
Closing issue #23

**Comment by leonardgithub** [comment]
@CharlesMangwa HI, CharlesMangwa, I saw there are some mapping in the .flowconfig, is it the reason?

**Comment by CharlesMangwa** [comment]
Hi! If you're talking about the aliases: nope, it's 2 different things. The `.flowconfig` file defines all the rules for Flow, the static type checker we use (documentation about this feature is [here](https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next#flow)).

**Comment by CharlesMangwa** [comment]
Hi @leonardgithub! If you're talking about the aliases: nope, it's 2 different things. The `.flowconfig` file defines all the rules for Flow, the static type checker we use (documentation for this feature right [there](https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next#flow)).

**Comment by leonardgithub** [comment]
@CharlesMangwa Thank you very much!  [https://github.com/LeoLeBras/react-apollo-example/issues/8](https://github.com/LeoLeBras/react-apollo-example/issues/8)
