### ISSUE TITLE
Crash on export ipx

### ISSUE THREAD

**Issue by lucifer1986** [LeoLeBras/react-native-redux-starter-kit#24]
Hi

I downloaded the latest source code without any modification and run it in my xcode(both iOS emulator and my iPhone 5s) and it works perfectly, but when I tried to export an ipx file for adHoc or development, the app crash immediately after I opened it on my iPhone 5s. I use the following way to export the ipx:
https://facebook.github.io/react-native/releases/0.31/docs/running-on-device-ios.html
https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/TestingYouriOSApp/TestingYouriOSApp.html

And I tried different options like "Ad Hoc Deployment" and "Development Deployment", For all compatible device and for specific device, re-build for bitcode or not. It still crashes. So I guess the way to export ipx could be different than a ordinary react-native project, could anyone share some clue?

Crash log attached.
[Crash-log-9-10-16, 10-34 AM.txt](https://github.com/LeoLeBras/react-native-redux-starter-kit/files/465458/Crash-log-9-10-16.10-34.AM.txt)

**Comment by kiranruth** [comment]
Any update on this ? Facing same issue.
-TIA

**Comment by ldom** [comment]
I think I had a similar issue and it comes from Reactotron. There are ways to tweak the settings to make this work but the simplest thing is to remove Reactotron. Do an `npm uninstall --save-dev reactotron`, then edit the `src/store/create.js` to remove the reactotron bits.

**Comment by lucifer1986** [comment]
Many thanks, Idom, you suggestion works like a charm, now I could deploy adhoc ipa to my iphone!

**Comment by CharlesMangwa** [comment]
Hi guys! @ldom is right yeah: simply removing `Reactotron` should resolve this bug. Sorry about that!

**Comment by CharlesMangwa** [comment]
Closing issue #24
