### ISSUE TITLE
Element type is invalid error

### ISSUE THREAD

**Issue by ldom** [LeoLeBras/react-native-redux-starter-kit#25]
Hi Léo,

Really like your starter kit, it's great. 

I'm getting random "Element type is invalid .../... but got: undefined" errors.

I have tried many things but to no avail.

The following piece of code, applied to a fresh copy of the kit, produces the error on my mac:

File `@containers/LaunchContainer/index.js`:

``` javascript
/* @flow */

import React, { Component, Text, View } from 'react'
import Container from '@components/Container'

class LaunchContainer extends Component<void, void, void> {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <Container>
        <Text>
          Thing
        </Text>
      </Container>
    )
  }
}

export default LaunchContainer
```

As you can see, I've tried to reduce the issue to the minimum and in the debugger, the issue arises when evaluating the Text element. I don't think it's a problem with Text, as in other files, I get the error with TouchableOpacity.

Any ideas?

Thanks,
Laurent

**Comment by LeoLeBras** [comment]
Hi @ldom ,

`<Text />` must be imported from `react-native`.

Try that : 

```
/* @flow */

import React from 'react'
import { Text } from 'react-native'
import Container from '@components/Container'

const LaunchContainer = (): React$Element<any> => (
  <Container>
    <Text>
      Thing
    </Text>
  </Container>
)

export default LaunchContainer
```

Léo

**Comment by ldom** [comment]
Whaoo such a stupid mistake, thanks a lot.
