### ISSUE TITLE
iOS app start issues

### ISSUE THREAD

**Issue by Ollebolle** [LeoLeBras/react-native-redux-starter-kit#27]
Hey, this seems like a great starter-kit. Although I'm getting 2 errors when trying to launch it from xcode (8.1):

### 1.
```/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute```

### 2.

```/Users/Olle/development/reactNativeReduxTest/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: Ignoring return value of function declared with warn_unused_result attribute```

Any ideas? Would love to try this one out! :)

**Comment by CharlesMangwa** [comment]
Hi @Ollebolle! Thanks for your feedback! Did you run a `git checkout next` right after your `git clone` to make sure that you're using the latest version of the start-kit? I know we didn't expressly mentioned it in the doc, I just corrected that.

**Comment by Ollebolle** [comment]
@CharlesMangwa Thank you! That did the trick!

**Comment by CharlesMangwa** [comment]
Glad to read that!

Closing issue #27
