### ISSUE TITLE
Issues with the starter kit

### ISSUE THREAD

**Issue by JeffreyLeeSpokeo** [LeoLeBras/react-native-redux-starter-kit#31]
I am sorry, but I really feel like this was not tested out at all. I copied over the src folder and package.json and ran into issues

1. The folder in containers is named wrong. It is LauchContainer and should be LaunchContainer
2. I believe there should be brackets around counter in the reducers file, {counter}
3. Reactotron seems to have a dependency on 'socket.io-client'. I tried to add that dependency to my package.json, but that still didn't work. Either way, it causes issues right now.

**Comment by markau** [comment]
I have an older version of the **next** branch that works fine, however, when cloning this repo recently I also experienced the `socket.io-client` issue and could not get the project to run.

**Comment by CharlesMangwa** [comment]
Fixed with https://github.com/LeoLeBras/react-native-redux-starter-kit/commit/1f5353e5f6df53717c92f08adb72fae7a8bddb94 🙂.
