### ISSUE TITLE
tons of flow errors

### ISSUE THREAD

**Issue by jtmarmon** [LeoLeBras/react-native-redux-starter-kit#32]
cloning the project, checking out `next` and running `flow` throw hundreds of flow errors. Is this intentional?

**Comment by CharlesMangwa** [comment]
Are these errors related to the `/src` folder or to `/node_modules`?

**Comment by jtmarmon** [comment]
both, but most of them are node_modules.

**Comment by jtmarmon** [comment]
ok, so a bunch of errors were coming from node_modules. many were from react-native itself, but instantiating a fresh RN project doesn't come with any flow errors. after seeing this, i just copied the .flowconfig from a default RN project into my directory, and that solved a lot of the errors.

the second batch of errors comes from react-native-experimental-navigation, which has many flow errors (see [here](https://github.com/aksonov/react-native-experimental-navigation/issues?q=is%3Aissue+is%3Aclosed)). The solution here  was just to add `.*/node_modules/react-native-experimental-navigation/.*` to my ignore section of `.flowconfig`.

That leaves on 15 errors which are all in the actual project src, rather than dependencies (which is sane and fixable, thankfully)

**Comment by jtmarmon** [comment]
oh i forgot to mention i had to downgrade everything to flow 0.38.0 (package.json and .flowconfig). this makes sense: react native 0.42.0 uses flow 0.38.0, not 0.42.0

**Comment by CharlesMangwa** [comment]
Just fixed all the project errors (https://github.com/LeoLeBras/react-native-redux-starter-kit/commit/b2006656e1486f437771cd0d071a1997b88e4f89) and switched to RN default config (https://github.com/LeoLeBras/react-native-redux-starter-kit/commit/92ab86bca4b5a376393360b7edfc9535ac241827). Just have these 16 errors now, but they seem to be RN related though.

**Comment by jtmarmon** [comment]
@CharlesMangwa I have only one error now (pulling on `next`)

![image](https://cloud.githubusercontent.com/assets/4528076/24318580/27aec91a-10de-11e7-86ad-d53be3862290.png)

**Comment by CharlesMangwa** [comment]
Well, you should be able to fix this one easily 👍
