### ISSUE TITLE
How do I get instant webpack style live reload to work?

### ISSUE THREAD

**Issue by faceyspacey** [LeoLeBras/react-native-redux-starter-kit#7]
It seems to only have the refresh style reloading. Is there a way to, say, if I'm editing the colors of something, to see the updates instantly? I notice it's not using webpack--would that be the solution?

**Comment by LeoLeBras** [comment]
Hello @faceyspacey, 

You can use react-transform-hmr to enable hot reloading. Check out [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server#user-content-hot-module-replacement). But HMR currently doesn't work using React Native >=0.12 with webpack. 
Fortunately, React Native is getting hot reloading in near future, see : [24c908e](https://github.com/facebook/react-native/commit/4ffb24164712c0f0cafc7c097a0cdbc80e2c04d1) and [HMR issues](https://github.com/facebook/react-native/issues?utf8=✓&q=%5Bhmr%5D). I can't wait to use HMR with React Native ... developer experience is going to be awesome 🙌 !

Léo

**Comment by faceyspacey** [comment]
awesome, thanks so much for the response!
