### ISSUE TITLE
react-native-router-flux can not performance perfectly

### ISSUE THREAD

**Issue by heimuya** [LeoLeBras/react-native-redux-starter-kit#9]
@LeoLeBras can you show some cases for how to use react-native-router-flux in this package? Thank you. Maybe this question should post in react-native-router-flux

**Comment by LeoLeBras** [comment]
Can you give me more details? 
You can see a detailled example provided in this package [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/DETAILED_EXAMPLE.md).

**Comment by jamesone** [comment]
`RNRF` isn't considered `stable` as it's based off the new `React-native` nav api, although it's still quite solid to use and will only get better as more code is pushed to the repo.

**Comment by CharlesMangwa** [comment]
Closing issue #9
